### ISSUE TITLE
RelayCommand<T> оправдан ли?

### ISSUE THREAD

**Issue by AndrewNowosad** [vladd/EvalUITest#1]
Оправдано ли использование дженерика в таком виде? Execute и CanExecute чаще всего имеют параметры разных типов

**Comment by vladd** [comment]
@AndrewNowosad Хм, а можете привести пример, в котором нужны разные типы для `Execute` и `CanExecute`? У меня обычно используется обрезанная версия, в которой `CanExecute` всегда `True`. Например, как здесь: https://ru.stackoverflow.com/a/616413/10105

**Comment by AndrewNowosad** [comment]
Хм, я походу погорячился, пример сходу (и не сходу тоже) привести не могу. Обычно всё же либо нужен `CanExecute`, всегда возвращающий `true`, либо `Execute` и/или `CanExecute` вообще без параметров. Так что - да, в принципе, дженерик такой имеет место.

**Comment by vladd** [comment]
@AndrewNowosad Вы правы насчёт того, что стоит добавить вариант без параметров — он часто нужен. Так и сделаю, спасибо!
